// pokemon_moves_data.hpp
#pragma once
#include "psyduck_extension.hpp"
#include <vector>
#include <string>

namespace duckdb {

struct Item {
	int id;
	std::string name;
	std::string category;
	std::string description;
	std::string location;
	int price;
};

std::vector<Item> items = {
    {1, "ANTIDOTE", "Status Heal", "Cures poison", "PokéMart Viridian Forest", 100},
    {2, "AWAKENING", "Status Heal", "Cures sleep", "PokéMart Pokémon Tower", 250},
    {3, "BICYCLE", "Key Item", "Allows you to travel faster", "Cerulean Bike Shop", 1000000},
    {4, "BIKE VOUCHER", "Key Item", "Used to get a FREE Bike", "Vermillion Pokémon Fan Club", 0},
    {5, "BURN HEAL", "Status Heal", "Heals burns", "PokéMart", 250},
    {6, "CALCIUM", "Stat Boost", "Increases Special level", "Silph Co. Route 13 Pokémon Mansion Celadon Dept. Store",
     9800},
    {7, "CARBOS", "Stat Boost", "Increases Speed level",
     "Silph Co. Safari Zone Power Plant Pokémon Mansion Celadon Dept. Store", 9800},
    {8, "CARD KEY", "Key Item", "Unlocks Silph Co. doors", "Silph Co. 5th Floor", 0},
    {9, "COIN", "Currency", "Slot Machine money", "Game Corner", 50},
    {10, "COIN CASE", "Key Item", "Holds coins", "Celadon Restaurant", 0},
    {11, "DIRE HIT", "Battle Item", "Increases attack effectiveness", "Celadon Dept. Store", 0},
    {12, "DOME FOSSIL", "Fossil", "Changes into Kabuto", "Mt. Moon", 0},
    {13, "ELIXER", "PP Restore", "Gives 10 PP to all Attacks", "Pokémon Tower", 0},
    {14, "ESCAPE ROPE", "Field Item", "Used to escape an area",
     "PokéMart Mt. Moon Game Corner Pokémon Tower Silph Co. Pokémon Mansion", 550},
    {15, "ETHER", "PP Restore", "Gives 10 PP to one Ability", "Different Areas S.S. Anne", 0},
    {16, "EXP. ALL", "Key Item", "Shares experience points", "Route 15", 0},
    {17, "FIRE STONE", "Evolution", "Evolves some Fire Pokémon", "Celadon Dept. Store", 2100},
    {18, "FRESH WATER", "Healing", "Quenches thirsts Restores 50 HP", "Celadon Dept. Store Roof", 200},
    {19, "FULL HEAL", "Status Heal", "Cures any ailments", "PokéMart Silph Co. Victory Road", 600},
    {20, "FULL RESTORE", "Healing", "Cures any ailments Restores all HP",
     "PokéMart Safari Zone Pokémon Mansion Cerulean Cave", 3000},
    {21, "GOLD TEETH", "Key Item", "Helps Warden to Speak", "Safari Zone 3", 0},
    {22, "GOOD ROD", "Key Item", "Used to fish", "Fuchsia City", 0},
    {23, "GREAT BALL", "Pokéball", "More Effective than a Pokéball", "PokéMart S.S. Anne", 600},
    {24, "GUARD SPEC.", "Battle Item", "Disables Special Attacks", "Celadon Dept. Store Victory Road", 700},
    {25, "HELIX FOSSIL", "Fossil", "Changes into Omanyte", "Mt. Moon", 0},
    {26, "HP UP", "Stat Boost", "Increases HP by 1",
     "Route 2 Mt. Moon Game Corner Celadon Dept. Store Pokémon Tower Silph Co. Power Plant", 0},
    {27, "HYPER POTION", "Healing", "Restores 200 HP", "PokéMart Game Corner Silph Co.", 1500},
    {28, "ICE HEAL", "Status Heal", "Heals frozen Pokémon", "PokéMart", 250},
    {29, "IRON", "Stat Boost", "Increases Defense level", "Game Corner Route 12 Pokémon Mansion Celadon Dept. Store",
     9800},
    {30, "ITEM FINDER", "Key Item", "Finds Hidden Items", "Route 11", 0},
    {31, "LEAF STONE", "Evolution", "Evolves some Grass Pokémon", "Celadon Dept. Store", 2100},
    {32, "LEMONADE", "Healing", "Quenches thirst Restores 80 HP", "Celadon Dept. Store Roof", 350},
    {33, "LIFT KEY", "Key Item", "Activates Game Corner Elevator", "Game Corner", 0},
    {34, "MASTER BALL", "Pokéball", "Catches Pokémon 100% of time", "Silph Co.", 0},
    {35, "MAX ELIXER", "PP Restore", "Restores all PP", "Various Areas Cerulean Cave", 0},
    {36, "MAX ETHER", "PP Restore", "Restores all PP of 1 ability", "Various Areas S.S. Anne", 0},
    {37, "MAX POTION", "Healing", "Restores all HP", "PokéMart S.S. Anne Safari Zone Pokémon Mansion", 2500},
    {38, "MAX REPEL", "Field Item", "Prevents wild Pokémon from attacking", "PokéMart", 700},
    {39, "MAX REVIVE", "Revival", "Revives Restores all HP", "Silph Co. Safari Zone Victory Road Cerulean Cave", 0},
    {40, "MOON STONE", "Evolution", "Evolves some Pokémon", "Mt. Moon Route 2 Game Corner Pokémon Mansion", 0},
    {41, "NUGGET", "Valuable", "Sold for 5000",
     "Various Areas Nugget Bridge Game Corner Pokémon Tower Safari Zone Cerulean Cave", 0},
    {42, "OAK'S PARCEL", "Key Item", "Exchange for Pokédex", "Viridian City PokéMart", 0},
    {43, "OLD AMBER", "Fossil", "Changes into Aerodactyl", "Pewter City Museum", 0},
    {44, "OLD ROD", "Key Item", "Fish for Magikarp", "Vermillion City", 0},
    {45, "PARALYZE HEAL", "Status Heal", "Heals Paralysis", "PokéMart", 200},
    {46, "POKÉBALL", "Pokéball", "Lowest odds of catching Pokémon", "PokéMart Viridian Forest", 200},
    {47, "POKÉDEX", "Key Item", "Records Pokémon Data", "Pallet Town", 0},
    {48, "POKÉDOLL", "Battle Item", "Distracts Opponents Makes girls happy", "Celadon Dept. Store", 1000},
    {49, "POKÉFLUTE", "Key Item", "Wakes sleeping Pokémon", "Pokémon Tower", 0},
    {50, "POTION", "Healing", "Restores 20 HP", "PokéMart Pallet Town Route 1 Viridian City Viridian Forest Mt. Moon",
     300},
    {51, "PP UP", "Stat Boost", "Increases PP by 1", "Various Areas Cerulean Cave", 0},
    {52, "PROTEIN", "Stat Boost", "Increases Attack level", "Celadon Dept. Store Silph Co. Route 13 Safari Zone", 9800},
    {53, "RARE CANDY", "Stat Boost", "Increases Exp Level by 1",
     "Mt. Moon Cerulean City S.S. Anne Game Corner Pokémon Tower Silph Co. Power Plant Pokémon Mansion Victory Road "
     "Cerulean Cave",
     0},
    {54, "REPEL", "Field Item", "Prevents wild Pokémon from attacking", "PokéMart", 350},
    {55, "REVIVE", "Revival", "Revives fainted Pokémon", "PokéMart", 1500},
    {56, "S.S. TICKET", "Key Item", "Used to Board S.S. Anne", "Sea Cottage", 0},
    {57, "SAFARI BALL", "Pokéball", "Used in Safari Zone (30 balls)", "Safari Zone", 1000},
    {58, "SECRET KEY", "Key Item", "Unlocks Cinnabar Island Gym", "Pokémon Mansion", 0},
    {59, "SILPH SCOPE", "Key Item", "Used to identify Ghosts", "Game Corner", 0},
    {60, "SODA POP", "Healing", "Quenches Thirsts Restores 60 HP", "Celadon Dept. Store Roof", 300},
    {61, "SUPER POTION", "Healing", "Restores 50 HP", "PokéMart Game Corner", 700},
    {62, "SUPER REPEL", "Field Item", "Prevents wild Pokémon from attacking", "PokéMart", 500},
    {63, "SUPER ROD", "Key Item", "Fishes for Pokémon", "Route 12", 0},
    {64, "THUNDER STONE", "Evolution", "Evolves Pikachu", "Celadon Dept. Store", 2100},
    {65, "TOWN MAP", "Key Item", "Shows you where you are", "Rival's House", 0},
    {66, "ULTRA BALL", "Pokéball", "Better than Great Balls", "PokéMart Cerulean Cave", 1200},
    {67, "WATER STONE", "Evolution", "Evolves some water Pokémon", "Celadon Dept. Store", 2100},
    {68, "X ACCURACY", "Battle Item", "Boosts Accuracy Temporarily", "Pokémon Tower Silph Co. Celadon Dept. Store",
     950},
    {69, "X ATTACK", "Battle Item", "Boosts Attack Temporarily", "Celadon Dept. Store", 500},
    {70, "X DEFEND", "Battle Item", "Boosts Defense Temporarily", "Celadon Dept. Store", 550},
    {71, "X SPECIAL", "Battle Item", "Boosts Special Temporarily", "Celadon Dept. Store", 350},
    {72, "X SPEED", "Battle Item", "Boosts Speed Temporarily", "Celadon Dept. Store", 350},
    {73, "TM01", "TM", "Teaches Mega Punch", "Mt. Moon Celadon City Store", 3000},
    {74, "TM02", "TM", "Teaches Razor Wind", "Celadon City Store Game Corner", 2000},
    {75, "TM03", "TM", "Teaches Swords Dance", "Silph Co.", 0},
    {76, "TM04", "TM", "Teaches Whirlwind", "Route 4", 0},
    {77, "TM05", "TM", "Teaches Mega Kick", "Victory Road Celadon City Store", 3000},
    {78, "TM06", "TM", "Teaches Toxic", "Fuchsia City Gym", 0},
    {79, "TM07", "TM", "Teaches Horn Drill", "Celadon City Store Game Corner", 2000},
    {80, "TM08", "TM", "Teaches Body Slam", "S.S. Anne", 0},
    {81, "TM09", "TM", "Teaches Take Down", "Saffron City Celadon City Store", 3000},
    {82, "TM10", "TM", "Teaches Double Edge", "Game Corner", 0},
    {83, "TM11", "TM", "Teaches Bubble Beam", "Cerulean City Gym", 0},
    {84, "TM12", "TM", "Teaches Water Gun", "Mt. Moon", 0},
    {85, "TM13", "TM", "Teaches Ice Beam", "Celadon City Store Roof", 0},
    {86, "TM14", "TM", "Teaches Blizzard", "Pokémon Mansion", 0},
    {87, "TM15", "TM", "Teaches Hyper Beam", "Celadon City Game Corner", 0},
    {88, "TM16", "TM", "Teaches Pay Day", "Route 12", 0},
    {89, "TM17", "TM", "Teaches Submission", "Victory Road Celadon City Store", 3000},
    {90, "TM18", "TM", "Teaches Counter", "Celadon City Store", 3000},
    {91, "TM19", "TM", "Teaches Seismic Toss", "Route 25", 0},
    {92, "TM20", "TM", "Teaches Rage", "Route 15", 0},
    {93, "TM21", "TM", "Teaches Mega Drain", "Celadon City Gym", 0},
    {94, "TM22", "TM", "Teaches Solar Beam", "Pokémon Mansion", 0},
    {95, "TM23", "TM", "Teaches Dragon Rage", "Celadon City Game Corner", 0},
    {96, "TM24", "TM", "Teaches Thunderbolt", "Vermilion Gym", 0},
    {97, "TM25", "TM", "Teaches Thunder", "Power Plant", 0},
    {98, "TM26", "TM", "Teaches Earthquake", "Silph Co.", 0},
    {99, "TM27", "TM", "Teaches Fissure", "Viridian City Gym", 0},
    {100, "TM28", "TM", "Teaches Dig", "Cerulean City", 0},
    {101, "TM29", "TM", "Teaches Psychic", "Saffron City", 0},
    {102, "TM30", "TM", "Teaches Teleport", "Route 9", 0},
    {103, "TM31", "TM", "Teaches Mimic", "Saffron City", 0},
    {104, "TM32", "TM", "Teaches Double Team", "Fuchsia City Celadon City Store", 1000},
    {105, "TM33", "TM", "Teaches Reflect", "Power Plant Celadon City Store", 1000},
    {106, "TM34", "TM", "Teaches Bide", "Pewter City Gym", 0},
    {107, "TM35", "TM", "Teaches Metronome", "Cinnabar Island", 0},
    {108, "TM36", "TM", "Teaches SelfDestruct", "Silph Co.", 0},
    {109, "TM37", "TM", "Teaches Egg Bomb", "Fuchsia City Celadon City Store", 2000},
    {110, "TM38", "TM", "Teaches Fire Blast", "Cinnabar Island Gym", 0},
    {111, "TM39", "TM", "Teaches Swift", "Route 12", 0},
    {112, "TM40", "TM", "Teaches Skull Bash", "Safari Zone", 0},
    {113, "TM41", "TM", "Teaches Softboiled", "Celadon City", 0},
    {114, "TM42", "TM", "Teaches Dream Eater", "Viridian City", 0},
    {115, "TM43", "TM", "Teaches Sky Attack", "Victory Road", 0},
    {116, "TM44", "TM", "Teaches Rest", "S.S. Anne", 0},
    {117, "TM45", "TM", "Teaches Thunder Wave", "Route 24", 0},
    {118, "TM46", "TM", "Teaches Psywave", "Saffron City Gym", 0},
    {119, "TM47", "TM", "Teaches Explosion", "Victory Road", 0},
    {120, "TM48", "TM", "Teaches Rock Slide", "Celadon City Store", 2000},
    {121, "TM49", "TM", "Teaches Tri Attack", "Celadon City Store", 2000},
    {122, "TM50", "TM", "Teaches Substitute", "Celadon City Game Corner", 0},
    {123, "HM01", "HM", "Teaches Cut", "S.S. Anne", 0},
    {124, "HM02", "HM", "Teaches Fly", "Route 16", 0},
    {125, "HM03", "HM", "Teaches Surf", "Fuchsia City Safari Zone", 0},
    {126, "HM04", "HM", "Teaches Strength", "Fuchsia City", 0},
    {127, "HM05", "HM", "Teaches Flash", "Route 2", 0}};

} // namespace duckdb
