#pragma once
#include <vector>
#include <optional>
#include <string>

namespace duckdb {

enum class PokemonType {
	Bug,
	Dark,
	Dragon,
	Electric,
	Fighting,
	Fire,
	Flying,
	Ghost,
	Grass,
	Ground,
	Ice,
	Normal,
	Poison,
	Psychic,
	Rock,
	Steel,
	Water
};

struct Move {
	const char *name;
	std::string type;
	std::optional<int> power;
	std::optional<int> accuracy;
	std::optional<int> pp;
};

static inline const std::vector<Move> &GetGen1Moves() {
	static const std::vector<Move> moves = {{"Absorb", "Grass", 20, 100, 25},
	                                        {"Acid", "Poison", 40, 100, 30},
	                                        {"Acid Armor", "Poison", std::nullopt, std::nullopt, 20},
	                                        {"Agility", "Psychic", std::nullopt, std::nullopt, 30},
	                                        {"Amnesia", "Psychic", std::nullopt, std::nullopt, 20},
	                                        {"Aurora Beam", "Ice", 65, 100, 20},
	                                        {"Barrage", "Normal", 15, 85, 20},
	                                        {"Barrier", "Psychic", std::nullopt, std::nullopt, 20},
	                                        {"Bide", "Normal", std::nullopt, std::nullopt, 10},
	                                        {"Bind", "Normal", 15, 85, 20},
	                                        {"Bite", "Normal", 60, 100, 25},
	                                        {"Blizzard", "Ice", 120, 90, 5},
	                                        {"Body Slam", "Normal", 85, 100, 15},
	                                        {"Bone Club", "Ground", 65, 85, 20},
	                                        {"Bonemerang", "Ground", 50, 90, 10},
	                                        {"Bubble", "Water", 20, 100, 30},
	                                        {"Bubble Beam", "Water", 65, 100, 20},
	                                        {"Clamp", "Water", 35, 75, 10},
	                                        {"Comet Punch", "Normal", 18, 85, 15},
	                                        {"Confuse Ray", "Ghost", std::nullopt, 100, 10},
	                                        {"Confusion", "Psychic", 50, 100, 25},
	                                        {"Constrict", "Normal", 10, 100, 35},
	                                        {"Conversion", "Normal", std::nullopt, std::nullopt, 30},
	                                        {"Counter", "Fighting", std::nullopt, 100, 20},
	                                        {"Crabhammer", "Water", 90, 85, 10},
	                                        {"Cut", "Normal", 50, 95, 30},
	                                        {"Defense Curl", "Normal", std::nullopt, std::nullopt, 40},
	                                        {"Dig", "Ground", 100, 100, 10},
	                                        {"Disable", "Normal", std::nullopt, 55, 20},
	                                        {"Dizzy Punch", "Normal", 70, 100, 10},
	                                        {"Double Kick", "Fighting", 30, 100, 30},
	                                        {"Double Slap", "Normal", 15, 85, 10},
	                                        {"Double Team", "Normal", std::nullopt, std::nullopt, 15},
	                                        {"Double-Edge", "Normal", 100, 100, 15},
	                                        {"Dragon Rage", "Dragon", std::nullopt, 100, 10},
	                                        {"Dream Eater", "Psychic", 100, 100, 15},
	                                        {"Drill Peck", "Flying", 80, 100, 20},
	                                        {"Earthquake", "Ground", 100, 100, 10},
	                                        {"Egg Bomb", "Normal", 100, 75, 10},
	                                        {"Ember", "Fire", 40, 100, 25},
	                                        {"Explosion", "Normal", 170, 100, 5},
	                                        {"Fire Blast", "Fire", 120, 85, 5},
	                                        {"Fire Punch", "Fire", 75, 100, 15},
	                                        {"Fire Spin", "Fire", 15, 70, 15},
	                                        {"Fissure", "Ground", std::nullopt, 30, 5},
	                                        {"Flamethrower", "Fire", 95, 100, 15},
	                                        {"Flash", "Normal", std::nullopt, 70, 20},
	                                        {"Fly", "Flying", 70, 95, 15},
	                                        {"Focus Energy", "Normal", std::nullopt, std::nullopt, 30},
	                                        {"Fury Attack", "Normal", 15, 85, 20},
	                                        {"Fury Swipes", "Normal", 18, 80, 15},
	                                        {"Glare", "Normal", std::nullopt, 75, 30},
	                                        {"Growl", "Normal", std::nullopt, 100, 40},
	                                        {"Growth", "Normal", std::nullopt, std::nullopt, 40},
	                                        {"Guillotine", "Normal", std::nullopt, 30, 5},
	                                        {"Gust", "Normal", 40, 100, 35},
	                                        {"Harden", "Normal", std::nullopt, std::nullopt, 30},
	                                        {"Haze", "Ice", std::nullopt, std::nullopt, 30},
	                                        {"Headbutt", "Normal", 70, 100, 15},
	                                        {"High Jump Kick", "Fighting", 85, 90, 20},
	                                        {"Horn Attack", "Normal", 65, 100, 25},
	                                        {"Horn Drill", "Normal", std::nullopt, 30, 5},
	                                        {"Hydro Pump", "Water", 120, 80, 5},
	                                        {"Hyper Beam", "Normal", 150, 90, 5},
	                                        {"Hyper Fang", "Normal", 80, 90, 15},
	                                        {"Hypnosis", "Psychic", std::nullopt, 60, 20},
	                                        {"Ice Beam", "Ice", 95, 100, 10},
	                                        {"Ice Punch", "Ice", 75, 100, 15},
	                                        {"Jump Kick", "Fighting", 70, 95, 25},
	                                        {"Karate Chop", "Normal", 50, 100, 25},
	                                        {"Kinesis", "Psychic", std::nullopt, 80, 15},
	                                        {"Leech Life", "Bug", 20, 100, 15},
	                                        {"Leech Seed", "Grass", std::nullopt, 90, 10},
	                                        {"Leer", "Normal", std::nullopt, 100, 30},
	                                        {"Lick", "Ghost", 20, 100, 30},
	                                        {"Light Screen", "Psychic", std::nullopt, std::nullopt, 30},
	                                        {"Lovely Kiss", "Normal", std::nullopt, 75, 10},
	                                        {"Low Kick", "Fighting", std::nullopt, 100, 20},
	                                        {"Meditate", "Psychic", std::nullopt, std::nullopt, 40},
	                                        {"Mega Drain", "Grass", 40, 100, 10},
	                                        {"Mega Kick", "Normal", 120, 75, 5},
	                                        {"Mega Punch", "Normal", 80, 85, 20},
	                                        {"Metronome", "Normal", std::nullopt, std::nullopt, 10},
	                                        {"Mimic", "Normal", std::nullopt, std::nullopt, 10},
	                                        {"Minimize", "Normal", std::nullopt, std::nullopt, 20},
	                                        {"Mirror Move", "Flying", std::nullopt, std::nullopt, 20},
	                                        {"Mist", "Ice", std::nullopt, std::nullopt, 30},
	                                        {"Night Shade", "Ghost", std::nullopt, 100, 15},
	                                        {"Pay Day", "Normal", 40, 100, 20},
	                                        {"Peck", "Flying", 35, 100, 35},
	                                        {"Petal Dance", "Grass", 70, 100, 20},
	                                        {"Pin Missile", "Bug", 14, 85, 20},
	                                        {"Poison Gas", "Poison", std::nullopt, 55, 40},
	                                        {"Poison Powder", "Poison", std::nullopt, 75, 35},
	                                        {"Poison Sting", "Poison", 15, 100, 35},
	                                        {"Pound", "Normal", 40, 100, 35},
	                                        {"Psybeam", "Psychic", 65, 100, 20},
	                                        {"Psychic", "Psychic", 90, 100, 10},
	                                        {"Psywave", "Psychic", std::nullopt, 80, 15},
	                                        {"Quick Attack", "Normal", 40, 100, 30},
	                                        {"Rage", "Normal", 20, 100, 20},
	                                        {"Razor Leaf", "Grass", 55, 95, 25},
	                                        {"Razor Wind", "Normal", 80, 75, 10},
	                                        {"Recover", "Normal", std::nullopt, std::nullopt, 20},
	                                        {"Reflect", "Psychic", std::nullopt, std::nullopt, 20},
	                                        {"Rest", "Psychic", std::nullopt, std::nullopt, 10},
	                                        {"Roar", "Normal", std::nullopt, std::nullopt, 20},
	                                        {"Rock Slide", "Rock", 75, 90, 10},
	                                        {"Rock Throw", "Rock", 50, 65, 15},
	                                        {"Rolling Kick", "Fighting", 60, 85, 15},
	                                        {"Sand Attack", "Normal", std::nullopt, 100, 15},
	                                        {"Scratch", "Normal", 40, 100, 35},
	                                        {"Screech", "Normal", std::nullopt, 85, 40},
	                                        {"Seismic Toss", "Fighting", std::nullopt, 100, 20},
	                                        {"Self-Destruct", "Normal", 130, 100, 5},
	                                        {"Sharpen", "Normal", std::nullopt, std::nullopt, 30},
	                                        {"Sing", "Normal", std::nullopt, 55, 15},
	                                        {"Skull Bash", "Normal", 100, 100, 15},
	                                        {"Sky Attack", "Flying", 140, 90, 5},
	                                        {"Slam", "Normal", 80, 75, 20},
	                                        {"Slash", "Normal", 70, 100, 20},
	                                        {"Sleep Powder", "Grass", std::nullopt, 75, 15},
	                                        {"Sludge", "Poison", 65, 100, 20},
	                                        {"Smog", "Poison", 20, 70, 20},
	                                        {"Smokescreen", "Normal", std::nullopt, 100, 20},
	                                        {"Soft-Boiled", "Normal", std::nullopt, std::nullopt, 10},
	                                        {"Solar Beam", "Grass", 120, 100, 10},
	                                        {"Sonic Boom", "Normal", std::nullopt, 90, 20},
	                                        {"Spike Cannon", "Normal", 20, 100, 15},
	                                        {"Splash", "Normal", std::nullopt, std::nullopt, 40},
	                                        {"Spore", "Grass", std::nullopt, 100, 15},
	                                        {"Stomp", "Normal", 65, 100, 20},
	                                        {"Strength", "Normal", 80, 100, 15},
	                                        {"String Shot", "Bug", std::nullopt, 95, 40},
	                                        {"Struggle", "Normal", 50, std::nullopt, std::nullopt},
	                                        {"Stun Spore", "Grass", std::nullopt, 75, 30},
	                                        {"Submission", "Fighting", 80, 80, 25},
	                                        {"Substitute", "Normal", std::nullopt, std::nullopt, 10},
	                                        {"Super Fang", "Normal", std::nullopt, 90, 10},
	                                        {"Supersonic", "Normal", std::nullopt, 55, 20},
	                                        {"Surf", "Water", 95, 100, 15},
	                                        {"Swift", "Normal", 60, std::nullopt, 20},
	                                        {"Swords Dance", "Normal", std::nullopt, std::nullopt, 30},
	                                        {"Tackle", "Normal", 35, 95, 35},
	                                        {"Tail Whip", "Normal", std::nullopt, 100, 30},
	                                        {"Take Down", "Normal", 90, 85, 20},
	                                        {"Teleport", "Psychic", std::nullopt, std::nullopt, 20},
	                                        {"Thrash", "Normal", 90, 100, 20},
	                                        {"Thunder", "Electric", 120, 70, 10},
	                                        {"Thunder Punch", "Electric", 75, 100, 15},
	                                        {"Thunder Shock", "Electric", 40, 100, 30},
	                                        {"Thunder Wave", "Electric", std::nullopt, 100, 20},
	                                        {"Thunderbolt", "Electric", 95, 100, 15},
	                                        {"Toxic", "Poison", std::nullopt, 85, 10},
	                                        {"Transform", "Normal", std::nullopt, std::nullopt, 10},
	                                        {"Tri Attack", "Normal", 80, 100, 10},
	                                        {"Twineedle", "Bug", 25, 100, 20},
	                                        {"Vine Whip", "Grass", 35, 100, 10},
	                                        {"Vise Grip", "Normal", 55, 100, 30},
	                                        {"Water Gun", "Water", 40, 100, 25},
	                                        {"Waterfall", "Water", 80, 100, 15},
	                                        {"Whirlwind", "Normal", std::nullopt, std::nullopt, 20},
	                                        {"Wing Attack", "Flying", 35, 100, 35},
	                                        {"Withdraw", "Water", std::nullopt, std::nullopt, 40},
	                                        {"Wrap", "Normal", 15, 85, 20}};
	return moves;
}

} // namespace duckdb
